# Site settings
# Meta tags
title: #Not used
description: #Not used

# Jekyll settings
baseurl: "" # Leave this blank unless your site is located on a subpath, e.g. /blog
url: "" # Typically http://www.yourdomain.org
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: 
  - README.md
